name: CI-Staging-Env
env:
  HOST: '173.198.252.200'
  PORT: 22
  USER: 'fiomarketplace'
  RM_DEPLOY_PATH: 'rm -r /home/fiomarketplace/www/middleware/staging/*'
  DEPLOY_PATH: '/home/fiomarketplace/www/middleware/staging'

on:
  pull_request:
    types:
      - opened
    branches:
      - 'releases/**'
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    name: Build and Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Build angular
        run: npm run build --configuration=production

      - name: Delete previous build
        uses: D3rHase/ssh-command-action@v0.2
        with:
          HOST: ${{ env.HOST }}
          PORT: ${{ env.PORT }}
          USER: ${{ env.USER }}
          PRIVATE_SSH_KEY: ${{ secrets.TEST_ENV_PRIV }}
          COMMAND: ${{ env.RM_DEPLOY_PATH }}

      - name: Upload Files
        id: upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          port: ${{ env.PORT }}
          username: ${{ env.USER }}
          localPath: './dist/fiomarketplace'
          remotePath: ${{ env.DEPLOY_PATH }}
          privateKey: ${{ secrets.TEST_ENV_PRIV }}
          privateKeyIsFile: false
